services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: true        # Services need to be public for testing

  Tourze\DeliveryAddressBundle\Repository\:
    resource: '../../Repository/'
  Tourze\DeliveryAddressBundle\Procedure\:
    resource: '../../Procedure/'
  Tourze\DeliveryAddressBundle\Controller\:
    resource: '../../Controller/'
  Tourze\DeliveryAddressBundle\Service\:
    resource: '../../Service/'
